### ISSUE TITLE
CLI fails to create new project

### ISSUE THREAD

**Issue by porras** [Rombusevil/sff#2]
Hi! I just wanted to try SFF because it looks great, but it fails to create a new project in my (Arch Linux) computer. If I interpret the error correctly, the reason might be that `/tmp` and my `/home` directory are not in the same device:

```
> sff-p8/cli/sff-cli.py -g project -n new_project
Traceback (most recent call last):
  File "sff-p8/cli/sff-cli.py", line 284, in <module>
    generate_new_project(args.path, args.name)
  File "sff-p8/cli/sff-cli.py", line 243, in generate_new_project
    os.rename(os.path.join(tmp_dir, file), os.path.join(proj_name, file))
OSError: [Errno 18] Invalid cross-device link: '/tmp/sff/win_state.lua' -> './new_project/win_state.lua'
```

If I ask to create the project under `/tmp` (to move it manually later), it seems to work correctly:

```
> sff-p8/cli/sff-cli.py -g project -n new_project -p /tmp
New project generated at /tmp/new_project
> mv /tmp/new_project/ .
> tree new_project/
new_project/
├── gameover_state.lua
├── game_state.lua
├── main.lua
├── menu_state.lua
├── sff
│   ├── buttons.lua
│   ├── collision.lua
│   ├── entity.lua
│   ├── explosions.lua
│   ├── timer.lua
│   └── tutils.lua
└── win_state.lua

1 directory, 11 files
```

That's an ok workaround but I'll give it a look to try a fix (no big expectations though, I have almost no experience in Python).

**Comment by Rombusevil** [comment]
Hey @porras, try using the script from the branch I just created called `tmphomedifffs` and let me know if that fixes it for you. If it does I merge it to master.

**Comment by porras** [comment]
Hi! Thanks for the quick reply. It still failed, I think it's because the `rename` you replaced wasn't the only one, but I used your change as a base for a fix, which I'll push in a minute, and which works for me at least!
